Repository Sleitnick/Knit, pull requests merged in 2020-12, with the labels that each got.

#21 README.md "Using Knit" fix
  README.md
Labels: documentation, size:small

#24 typeof(true|false) == "boolean" not "bool"
  src/Knit/Util/Remote/RemoteProperty.lua
Labels: bug

#20 Better table replication for RemoteProperty objects
  src/Knit/KnitClient.lua
  src/Knit/KnitServer.lua
  src/Knit/Util/Remote/RemoteProperty.lua
Labels: enhancement

#28 Add ability to execute function immediately in DelayRepeat
  docs/util.md
  src/Knit/Util/Symbol.lua
  src/Knit/Util/Thread.lua
Labels: enhancement
