Repository Sleitnick/Knit, pull requests merged in 2021-07, with the labels that each got.

#121 Fix self lint
  src/KnitClient.lua
Labels: bug

#120 Update services doc
  docs/services.md
Labels: documentation

#119 Fix copy and paste typo
  docs/vscodesnippets.md
Labels: documentation

#127 Remove redundant loop in Component module
  src/Util/Component.lua
Labels: enhancement
