Repository Sleitnick/Knit, pull requests merged in 2021-01, with the labels that each got.

#34 Rename RemoteEvent to RemoteSignal
  docs/services.md
  docs/util.md
  src/Knit/KnitClient.lua
  src/Knit/Util/Remote/RemoteSignal.lua
  test/tests/Specs/Knit.spec.lua
Labels: enhancement

#35 Fix Component & doc issue
  docs/controllers.md
  src/Knit/Util/Component.lua
Labels: documentation, enhancement

#36 Rename RemoteEvent to RemoteSignal in KnitServer
  src/Knit/KnitServer.lua
Labels: bug

#37 Server and Client modules for RemoteSignal and RemoteProperty
  docs/util.md
  src/Knit/KnitClient.lua
  src/Knit/Util/Remote/ClientRemoteProperty.lua
  src/Knit/Util/Remote/ClientRemoteSignal.lua
  src/Knit/Util/Remote/RemoteProperty.lua
  src/Knit/Util/Remote/RemoteSignal.lua
Labels: enhancement

#39 Add AutoServices and AutoControllers functions to Knit
  docs/examples.md
  docs/gettingstarted.md
  docs/knitapi.md
  docs/services.md
  docs/styleguide.md
  mkdocs.yml
  src/Knit/KnitClient.lua
  src/Knit/KnitServer.lua
  src/Knit/Util/EnumList.lua
  src/Knit/Util/Loader.lua
  src/Knit/Util/Thread.lua
  src/Knit/Version.txt
Labels: enhancement

#46 Remove ref to nil field
  src/Knit/Util/Remote/ClientRemoteProperty.lua
Labels: bug
